name: .NET Core Tests

on:
  push:
    branches: [ "main" ]
    paths: ['**.cs', '**.sln', '**.csproj', '**.proto']

  pull_request:
    branches: [ "main" ]
    paths: ['**.cs', '**.sln', '**.csproj', '**.proto']

  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '10.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore -c Release

    - name: Test
      run: dotnet test --no-build --verbosity normal -c Release

    - name: Setup Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.14'

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install grpcio grpcio-tools pytest

    - name: Generate Protobufs for Test
      run: |
        python -m grpc_tools.protoc -I./src/LevelBasedForaging.GrpcServer/Protos --python_out=./ExampleAgents --grpc_python_out=./ExampleAgents ./src/LevelBasedForaging.GrpcServer/Protos/foraging.proto
    
    - name: Run Python Integration Tests
      run: |
        pytest tests/PythonIntegration/test_python_agent.py --server-bin=./src/LevelBasedForaging.GrpcServer/bin/Release/net10.0/LevelBasedForaging.GrpcServer
